### ISSUE TITLE
Demo 不应该包含的代码

### ISSUE THREAD

**Issue by wujun4code** [leancloud/LeanMessage-Demo#10]
* 删除所有跟 NSUserDefaults 相关的调用，Demo 只保证一次运行是正确的即可，不需要存缓存，Demo 代码不需要考虑本地保留 ClientId 这种操作。

* `LoginViewController` 中 `openSessionAndGoMainViewController` 的方法里面实现的打开 session 和跳转到 MainViewController ，这段逻辑直接加到 onLoginButtonClicked 中即可，Demo 封装的越多越会对用户造成困扰， Demo 就是越简单越好，不是越专业越好。

* `MainViewController` 中的 `onChatButtonClicked` 中的调用 LeanMessageManager 的代码全都展示出来， LeanMessageManager 这个类**必须**在 Demo 中删除

**Comment by lzwjava** [comment]
* NSUserDefaults 是为了开发者调试用。应用能自动登录不单是为了用户方便，调试上也方便。直接跳转到主页面，进行相关调试。本来是没有的，后来手动输入登录多了，就弄了个轻量级的自动登录。

* fixed

* fixed
