### ISSUE TITLE
删除 loadMessagesWhenInit 以及 loadOldMessages 这 2 个实现

### ISSUE THREAD

**Issue by wujun4code** [leancloud/leanmessage-demo#14]
@lzwjava 

用户在阅读 Demo 代码的时候初衷是看我们如何发送消息和接收消息，对本地缓存这种只有生产代码才会出现的逻辑，我们的开发者在第一次接触的时候完全不需要出现在他们的视线范围内。
因为只要我们的消息准确送达，做不做缓存，怎么做缓存，高级开发者都有自己的一套逻辑，Demo 做这个展现有点多余。

**Comment by lzwjava** [comment]
支持这个还有个考虑是，可以看到很多人在上面发过消息。像网页版，如果进去什么都没有，你可能并不觉得它能正常收发消息，需要自己测一测，如果进去，看到一页都是别人发的消息，就会立马上手研究代码，而且感觉也不少人用，比较可靠。

这里用的是实时向服务端请求消息。等本地缓存出来后，我就换成我们提供的本地缓存的接口吧。

因为一般地，聊天不仅要考虑收发消息，还要考虑显示过去的消息。

**Comment by wujun4code** [comment]
我们关注的点就是 「登陆」 「发消息」 「接消息」 就这三个功能，核心展现，完全不需要用户在这三个功能之外再看见多余的代码，我再次强调，我们 LeanMessage 的卖点是实时通信，不是卖一个完整的通信产品逻辑。
我还是坚持删除跟以上3个功能无关的代码。

@jwfing
