### ISSUE TITLE
iOS的demo, 运行起来需要输入ID, ID从哪里获得呢?

### ISSUE THREAD

**Issue by JasonSDHY** [leancloud/leanmessage-demo#29]

**Comment by lzwjava** [comment]
参考 https://leancloud.cn/docs/realtime_v2.html#clientId

**Comment by JasonSDHY** [comment]
谢谢了,没登录进去是因为iOS9里面info.plist没改
    <key>NSAppTransportSecurity</key>
    <dict>
        <key>NSAllowsArbitraryLoads</key>
        <true/>
    </dict>
