### ISSUE TITLE
layout 在 ipad 下无法自适应

### ISSUE THREAD

**Issue by wujun4code** [leancloud/LeanMessage-Demo#3]
不做过多的效果渲染，但是 在 ipad 上的布局至少要是看着不别扭。
![image](https://cloud.githubusercontent.com/assets/5119542/7696473/4c45eee2-fe30-11e4-95f5-fd34de9c0306.png)

或者可以只支持 iphone ，ipad 的 界面效果就暂时不做，xcode 里面就把 这个项目改成仅仅支持 iphone 也没什么问题。

**Comment by lzwjava** [comment]
仅支持iphone，已修改。
