### ISSUE TITLE
界面效果需要完全符合 trello 上的界面

### ISSUE THREAD

**Issue by wujun4code** [leancloud/LeanMessage-Demo#4]
https://trello.com/c/tOyT9Tk2/56-demo-leanmessage-simple-demo

**Comment by lzwjava** [comment]
https://github.com/leancloud/LeanMessage-Demo/commit/d35ca8d80f603abd447e3c65f24caf499748a04e  iOS done

**Comment by lzwjava** [comment]
![ios simulator screen shot 2015 5 19 5 21 06](https://cloud.githubusercontent.com/assets/5022872/7699610/a766c6e6-fe4b-11e4-8378-d82d94a0b6c7.png)
![ios simulator screen shot 2015 5 19 5 21 24](https://cloud.githubusercontent.com/assets/5022872/7699613/a97a01a0-fe4b-11e4-941d-6b39c59b2f3e.png)
