### ISSUE TITLE
iOS Demo 运行起来界面是乱的

### ISSUE THREAD

**Issue by mattchen** [leancloud/leanmessage-demo#48]
只有登录界面是正常的，进入聊天室后界面就是乱的，界面上随便点进去单聊界面连输入框都没有。

Xcode 8.1，iOS Simulator 9.3 and 10.1

**Comment by BillBillBillBill** [comment]
同

**Comment by Cadillac-Hs** [comment]
官方做的很 烂啊

**Comment by zhouxincheng** [comment]
同上  界面是乱的

**Comment by leeyeh** [comment]
iOS 与 Android 的 UI 库请使用 ChatKit https://leancloud.cn/docs/chatkit-ios.html 
这个 demo 中的 iOS 与 Android Demo 将不再维护。
