### ISSUE TITLE
应用的名称必须改成 LeanMessageDemo，而不是现在的 Simple Chat

### ISSUE THREAD

**Issue by wujun4code** [leancloud/LeanMessage-Demo#5]
对外发布的 Demo 名称必须与对应的产品模块名称一模一样，这一点不允许有任何自定义的余地。
chat ，keepalive 这些完全不能与官方网站的功能能模块对应。

**Comment by lzwjava** [comment]
https://github.com/leancloud/LeanMessage-Demo/commit/d35ca8d80f603abd447e3c65f24caf499748a04e  iOS done

**Comment by lzwjava** [comment]
web 没改名，记录在这个 issue 吧， https://github.com/leancloud/LeanMessage-Demo/issues/6
