### ISSUE TITLE
消息接收，能不能像QQ一样显示某人已发来n条消息？

### ISSUE THREAD

**Issue by ysy950803** [leancloud/leanmessage-demo#50]
这个是用的推送，所以每条消息都会弹出来，一旦离线很久，就很多，但能不能在应用层怎么处理一下，让通知栏针对每个聊天对象只显示一条最新的消息或者所有对象都集合起来只显示一条通知，即未读消息数。

**Comment by leeyeh** [comment]
https://leancloud.cn/docs/realtime_guide-js.html#未读消息数更新通知
