### ISSUE TITLE
web 版的 demo 必须给与用户配置 appid 以及 appkey 的入口

### ISSUE THREAD

**Issue by wujun4code** [leancloud/leanmessage-demo#6]
开发者在配置完 ios 的 demo 之后，需要跟另一端进行联调，web 版就是最好的一个入口，那么 web 版的 demo 也必须跟 ios 有一致的用户体验，目前 web 版本是内置了一个应用的  appid 以及 appkey，这样是不对的。
所以在 release ios demo 之前 web demo 也必须重构。

**Comment by lzwjava** [comment]
跟 @wangxiao 讨论来，之前 是做了个可以填写 appId 和 appKey 、创建对话各种功能都有的版本，但用户很困惑，不如现在简单明了。打算旁边加个按钮，跳转至可以配置的另外一个页面。保持现在的主页。

**Comment by wujun4code** [comment]
好，web 版 由你继续完成？

**Comment by lzwjava** [comment]
还是请 @wangxiao  来吧， 我 js 挺渣的。。

**Comment by wujun4code** [comment]
@wangxiao 太忙了，我来吧。

**Comment by lzwjava** [comment]
赞！

PS：体验不用太完美，客户端怕跟不上~

**Comment by wangxiao** [comment]
昨天和 @lzwjava @sunng87  也讨论来着，最后的建议是：

*  做一个最简版本，为 demo1，就是和 Web 最简版本完全一致的； 
* 再做一个你们目前想做的版本，为 demo2；
* 所有 iOS 、Android 等 demo 都是应该上架或者用户非常简单可安装试用的。
