### ISSUE TITLE
代码中 LeanMessageManager 会对初学者造成困扰

### ISSUE THREAD

**Issue by wujun4code** [leancloud/LeanMessage-Demo#8]
```objc
NSString *otherId = self.otherIdTextField.text;
    if (otherId.length > 0) {
        [[LeanMessageManager manager] createConversationsWithClientIDs:@[otherId] conversationType:ConversationTypeOneToOne completion: ^(AVIMConversation *conversation, NSError *error) {
            if (error) {
                NSLog(@"error=%@", error);
            }
            else {
                [self performSegueWithIdentifier:@"toChat" sender:conversation];
            }
        }];
    }
```
这段代码会给初学者（第一次接触 LeanMessage 的开发者）造成困扰：为什么你们官方 SDK 不把 LeanMessageManager 集成进去？而在 Demo 里面还封装了一套业务逻辑？

@lzwjava 

我不建议 Demo 的代码需要遵照生产环境的逻辑严密性进行开发，Demo 只列出 SDK 最基本的接口，不需要做过多的逻辑判断。

**Comment by lzwjava** [comment]
毕竟开发者还是要拿去生产用，简单地把 LeanCloud 的相关逻辑都放到 LeanMessageManager，直接复制粘贴进开发者的项目更快。据我所知，不少用户都这么用。

**Comment by jwfing** [comment]
https://github.com/leancloud/LeanMessage-Demo/blob/master/iOS/LeanMessageDemo/LeanMessageDemo/LeanMessageManager.m#L6

这个头文件怎么是别人的？并且文件名和注释还不一样。

在 2015年5月22日 下午3:05，lzwjava <notifications@github.com>写道：

**Comment by lzwjava** [comment]
改过来了。

**Comment by lzwjava** [comment]
all fixed ，没有了 LeanMessageManager
