### ISSUE TITLE
无法安装包

### ISSUE THREAD

**Issue by SUNWUYUAN** [leancloud/leanmessage-demo#89]
我无法安装依赖，项目无法运行，我尝试了npm和yarn等工具，npm提示依赖错误
![image](https://user-images.githubusercontent.com/88357633/200114720-99292b22-b8a7-40c5-a3ba-8a392e29571a.png)
像这样👆

我手动删除了一些冲突的依赖，但它不断出现新的错误
![image](https://user-images.githubusercontent.com/88357633/200114751-5a11c601-70f0-4e24-b485-2f298d1a7318.png)
（我使用了node6.00、node6.9.2、node17.8.0、node18.12.1进行了尝试）
我应该如何安装并使用(仅仅是正常打开)这个项目？或者这个项目已经不再考虑维护了？

**Comment by SUNWUYUAN** [comment]
也许您可以告诉我您使用什么样的环境或方式部署成功了，我将十分感谢。

我已经尝试在网上搜索，没有任何结果

**Comment by leeyeh** [comment]
这个项目运行在 Node.js 8 并使用 yarn 作为包管理工具（README 有误刚订正了）。我试了一下 node@8.17.0 (Linux x64) + yarn@1.22.19  是可以正常 install 与 build 的。

>这个项目已经不再考虑维护了？

这个项目使用的一些技术栈已经过时了，但我们没有升级的打算。因为这个项目是 IM 服务的 demo，主要目的是展示常见功能的最佳实践，这部分并没有过时。
